### ISSUE TITLE
Automatically process submissions after getSubmissions() + revise how custom processing is defined inside apps

### ISSUE THREAD

**Issue by dave-mills** [stats4sd/laravel-odk-link#10]
Currently: 
- new submissions pulled in with the getSubmissions() are *not* automatically processed. 
- submission processing only occurs when a request is sent to the `submissions.process` route (this is only linked to the 'reprocess submissions' button in the submission crud controller list view).
- the app dev needs to add a `submissions.process` route, which is used for the reprocess submissions button.
  - this lets each app have its own custom processing scripts;
  - *but* it means we can't use those custom scripts when first pulling submissions from ODK Central.

TODO: 

1. Instead of defining a 'process_endpoint' as a route, we should ask the app developers to somehow define a 'process_method' / class, which accepts the Submission model object as a parameter.
   - This way, we can hook into this in multiple places.
2. After that, we can+should automatically process submissions when they are first pulled (`OdkLinkService::class`, `getSubmissions()`)
3. Swap the 'reprocess submission' button to reference a route inside the package, that calls the method defined in 1.

We should also add a method to "delete all `$submission->entries`  records", that runs before reprocessing submissions. (This would be hard to do before doing point 1 above). 

@ciara-mc - this should help with testing submissions. I'll look at doing this tomorrow; if you can push the latest changes that work with the Healthy Villages?

**Comment by ciara-mc** [comment]
I pushed my changes to the [submissions](https://github.com/stats4sd/laravel-odk-link/tree/submissions) branch
